### ISSUE TITLE
Tagging 1.2.0 and uploading to RubyGems

### ISSUE THREAD

**Issue by Kounotori-ssbm** [kaspergrubbe/ruby-vnc#23]
https://rubygems.org/gems/ruby-vnc/

ruby-vnc tagged 1.1.0 and upload on June 03, 2012 to RubyGems.
This project has merged some commits for long time, but it has not updated in RubyGems yet.
Is it about time to tag 1.2.0 and upload to RubyGems for ruby-vnc gem users!?

＊ please receive pull request #21 before this, I really need this 😁

**Comment by kaspergrubbe** [comment]
@aquasync Ping? :)

**Comment by aquasync** [comment]
Hi @kaspergrubbe. Sorry I guess this has become somewhat unmaintained - in fact I've not used this code in over a decade :). Happy to try and hand it over to you or one of the other recent contributors if you've an inclination. Can certainly just tag and upload but couldn't get the tests to run successfully just now - don't currently have docker setup to run the tests that hit up real vnc servers.

**Comment by kaspergrubbe** [comment]
@aquasync No worries, thanks for getting back to us :) I would like to take over if you wouldn't mind. 

My Rubygem account is this: https://rubygems.org/profiles/kaspergrubbe

**Comment by kaspergrubbe** [comment]
Hi @aquasync 

Hope you are doing well.

Do you have an idea of when you might have time to give me access?

**Comment by aquasync** [comment]
Hi, sorry to drop the ball on this - just had a crack at adding you as owner on rubygems.org. Let me know if that works?

**Comment by kaspergrubbe** [comment]
@aquasync No worries! It worked, I now have access to the gem on Rubygems, thanks! ♥️🎉

Do you want development to continue on https://github.com/aquasync/ruby-vnc or should I fork? 

I think I prefer to keep the discussions and PRs from this repo, so can you either give me write access to this repo on Github, or transfer ownership to me?

**Comment by aquasync** [comment]
Happy to just transfer, but it doesn't let me because kaspergrubbe/ruby-vnc already exists?

**Comment by kaspergrubbe** [comment]
@aquasync I've renamed it, can you try again? 👍

**Comment by kaspergrubbe** [comment]
@aquasync I hope you had a fantastic weekend, kind reminder about this issue. Can you try and transfer again?

**Comment by aquasync** [comment]
Unfortunately this time it gave me "kaspergrubbe already has a repository in the aquasync/ruby-vnc network"...

**Comment by kaspergrubbe** [comment]
@aquasync Ok I have now completely removed the repo, can you try again? 🥇

**Comment by kaspergrubbe** [comment]
Thank you! 

<img width="518" alt="Screenshot 2021-09-20 at 11 33 02" src="https://user-images.githubusercontent.com/334273/133981806-db170e9a-35fc-43c8-bb8f-d581f9467010.png">

**Comment by kaspergrubbe** [comment]
We have a new release: https://github.com/kaspergrubbe/ruby-vnc/releases/tag/v1.2.0 🎉

**Comment by aquasync** [comment]
Nice one!
